- Interview Problems/01-Array/Sort Array of 0,1,2 .cpp
**Paytm Question** 
It demands to sort array of 3 numbers in O(n) time Complexity.
Algorithm Used:  Dutch National Algorithm.
Note: This is not a redundant Code
> Paytm_Question_Sort_Array_0_1_2

- 22- Trie Data Structure/WordSearchll .cpp
> Create WordSearchll .cpp

- Interview Problems/01-Array/move_all_zeroes_to_end_array_Amazon.cpp
**Added the move_all_zeroes_to_end_array_Amazon.cpp Filename**
**Changes Proposed:** A cpp program to move all zeroes to end of array which is asked in Amazon.
> cpp program to move all zeroes to end of array

- 03-Arrays/transpose.cpp
added program to transpose a matrix
> added matrix transpose

- Interview Problems/02- LinkedList/nth_node_from_end_linkedlist_Walmart.cpp
**Added the nth_node_from_end_linkedlist_Walmart.cpp  Filename**
**Changes Proposed:** cpp pgm to find nth node from end of linkedlist asked in walmart
> cpp pgm to find nth node from end of list

- 09- Number Theory/BinaryExponentiation.cpp
- 09- Number Theory/Nth-Fibonacci.cpp
> Updated Number Theory

- Interview Problems/01-Array/Longest_Increasing_Subsequence_DP_Walmart.cpp
**Added the Longest_Increasing_Subsequence_DP_Walmart.cpp Filename**
** Changes Proposed:** cpp program to find length of LIS using dynamic programming
> cpp pgm to find length of LIS

- 10- Recursion & Backtracking/sort_a_stack.cpp
> Added sort a stack using recursion

- 18-Binary Tree/merge_two_binary_tree_node_sum.cpp
**Added the erge_two_binary_tree_node_sum.cpp Filename**
**Changes Proposed:** cpp pgm to merge two binary trees using node sum
> cpp pgm to merge two binary trees

- 18-Binary Tree/binary_to_DLL.cpp
** Added the binary_to_DLL.cpp **
> Added binary tree to doubly linked list

- 04-Sorting/radix_sort(souvick roy)/Radix_sort.cpp
<radix_sort.cpp>
** Changes Proposed <Describe> in the PR Describe **
Added radix sort algorithm for sorting
- [#] Yes
> Added radix sort algorithm

- 03-Arrays/rotatearr.txt
Here we solve a question related to array rotation. We are given an unsorted array and we need to rotate it by r elements clockwise.
T is the number of test cases, n is the number of elements of the array and r is the rotation number.
> added rotate array file

- 24- Dynamic Programming/longestCommonContiguousSubarray.cpp
**Added the longestCommonContiguousSubarray.cpp Filename**
**Changes Proposed:** cpp pgm to find longest common contiguous subarray sum using DP
> cpp pgm to find longest common contiguous subarray sum using DP

- 11-Some More Sorting/bubbleSort.cpp
- 18-Binary Tree/isBinary_BST.cpp
** Added the isBinary_BST.cpp *
** A program to check whether a binary tree is a binary search tree or not**
> Binary tree

- ONLINE JUDGE/LeetCode/#236-Lowest_Common_Ancestor_of_a_Binary_Tree.cpp
Program To find Lowest Common Ancestor Of a Binary Tree.
> LCA problem

- 03-Arrays/duplicate_arr.cpp
Here we have to find the duplicate numbers present in a given unsorted array and print them. If no duplicates are present we have to print output as -1.
>  find duplicates in array

- 03-Arrays/zeros_arr.cpp
We are given an unsorted array. We have to push all the zeroes in the array to the right side without affecting the order of the non zero elements.
> push zeroes to right

- ONLINE JUDGE/LeetCode/#226-Invert_Binary_Tree.cpp
Problem to Invert a Binary Tree.
> Inversion Of Binary Tree

- 15-Stack/Stack_Implementaion_O-1_time_complexity.cpp
**Added the Stack_Implementaion_O-1_time_complexity.cpp Filename**
**Changes Proposed:** cpp pgm to implement stack in O(1) time complexity
> cpp pgm to implement stack in O(1) time complexity

- ONLINE JUDGE/LeetCode/#200-Number-of-Islands.cpp
#13 
**Added the `#200-Number-of-Islands.cpp`**
**Changes Proposed in the PR**
> Uploaded solution to aforementioned leetcode problem
Read {%include Contributing.md%}
>  #200 Number-of-Islands Added

- 13- Linked Lists/palindrome_ll.cpp
In this program we check if the given Linked List is a palindrome or not and return 1 for Palindrome and 0 for not palindrome
> check palindrome in LL

- ONLINE JUDGE/LeetCode/#36 Valid Sudoku.cpp
** Added the 36. Valid Sudoku.cpp Filename **
** Uploaded solution to the problem
- [+] Yes
> 36. Valid Sudoku Solution in cpp

- ONLINE JUDGE/LeetCode/#1550:Three-Consecutive-Odds.cpp
Added 1550:Leetcode- Three-Consecutive-Odd
Included Code
> Added Leetcode Three Consecutive Odds.cpp

- ONLINE JUDGE/LeetCode/#62-Unique-Paths.cpp
> added leetcode problem as per #9

- ONLINE JUDGE/CodeChef Challenges/PSHTTR Pishty and tree.cpp
** Added the "PSHTTR Pishty and Tree.cpp" Filename **
> Added solution to Codechef problem PSHTTR

- ONLINE JUDGE/Hackerrank/#33-Accessing Inherited Functions.cpp
** Added the <Filename> Filename as**
Please review!!
> Added HackerRank solution of "Accessing Inherited Functions"

- ONLINE JUDGE/LeetCode/#1503 Last-Moment-Before-All-Ants-Fall-Out-Of-A-Plank.cpp
- ONLINE JUDGE/LeetCode/#319 Bulb Switcher.cpp
** Added the #1503 Last-Moment-Before-All-Ants-Fall-Out-Of-A-Plank.cpp  Filename as**
** Added the #319 Bulb Switcher.cpp  Filename as**
** Changes Proposed solutions to the problems on leetcode in the PR Describe
- [+] Yes
> Added 1503 and 319 problems on Leetcode

- ONLINE JUDGE/CodeChef Challenges/CHFNSWAP_SEPT20B.cpp
** Added the <Filename> Filename as**
CHFNSWAP_SEPT20B.cpp
Added Code
> Added Codechef Challenges

- ONLINE JUDGE/LeetCode/#204-count-primes.cpp
#13 
**Added the #204-count-primes.cpp**
**added leetcode solution file**
> added leetcode problems

- 10- Recursion & Backtracking/JosephusProblem.cpp
** Added the <Filename> Filename as**
JosephusProblem.cpp
> Added Josephus Problem

- ONLINE JUDGE/LeetCode/#384-Shuffle-An-Array.cpp
#13 
**Added the `#384-Shuffle-An-Array`**
> #384 Shuffle An Array added

- ONLINE JUDGE/LeetCode/#20-Valid-Parentheses.cpp
- ONLINE JUDGE/LeetCode/#33-Search-in-Rotated-Sorted-Array.cpp
> Created valid-Parentheses in online judge  as per #13

- ONLINE JUDGE/LeetCode/#1461-check_if_a_string_contains_all_binary_codes_of_size_k.cpp
> add solution to leetcode problem #1461

- ONLINE JUDGE/CodeChef Challenges/FFL_LTIME83B.cpp
- ONLINE JUDGE/CodeChef Challenges/LECANDY.cpp
- ONLINE JUDGE/CodeChef Challenges/PMLU_DEC19B.cpp
- ONLINE JUDGE/CodeChef Challenges/WATSCORE_DEC19B.cpp
* FFL_LTIME83B.cpp - https://www.codechef.com/LTIME83B/problems/FFL
* LECANDY.cpp - https://www.codechef.com/problems/LECANDY
* PMLU_DEC19B.cpp - https://www.codechef.com/DEC19B/problems/PLMU
* WATSCORE_DEC19B.cpp - https://www.codechef.com/DEC19B/problems/WATSCORE
As mentioned in #9 i've added solutions to 4 Codechef problems.
> Added 4 Codechef Solutions

- ONLINE JUDGE/LeetCode/#127-Word-Ladder.cpp
> added world ladder problem as per #13

- ONLINE JUDGE/LeetCode/#12-Integer_to_Roman.cpp
#13 
**Added the `#12-Integer_to_Roman.cpp`**
Added solution to LeetCode problem 12.
> add solution to LeetCode #12

- 23- Greedy Algorithms/EgyptianFraction.cpp
**Added the  Filename as**
EgyptianFraction.cpp
> Added Greedy Algorithm For Egyptian Fraction

- 08-Vector/erase.cpp
erase.cpp
Added an example of the use of erase() of vectors, to the 08-Vectors folder.
> Added erase() of vectors

- ONLINE JUDGE/LeetCode/#231-Power_Of_Two.cpp
- ONLINE JUDGE/LeetCode/#771-Jewels_And_Stones.cpp
#771-Jewels_And_Stones.cpp
I have added the solution class for the problem #771 -
'Jewels and Stones'. It has runtime: 0ms and
memory usage: 6.4MB
> Added problem #771 - Jewels and Stones

- 06-Bit Manipulation/Unique Bitwise OR of subarrays.cpp
- 09- Number Theory/Binary Multiplication.cpp
> Added two new Algorithms in Bit Manipulation and Number Theory

- 23- Greedy Algorithms/GasUp.cpp
Added the Filename as
GasUp.cpp
I am assuring that the file is not redundant and making the Pull Request
> Added GasUp problem in Greedy Algorithms

- 24- Dynamic Programming/Job_Scheduling.cpp
- 24- Dynamic Programming/Job_Sheduling.cpp
- 24- Dynamic Programming/Weighted_Job_Scheduling.cpp
Job_Scheduling.cpp
Weighted_Job_Scheduling.cpp
I have added solutions for job scheduling problems weighted and unweighted. 
> Added two Scheduling Problems in Dyanamic Programming

- 04-Sorting/MergeSort.cpp
MergeSort algorithm added
MergeSort.cpp
- [ x] Yes
> Merge sort algorithm added

- ONLINE JUDGE/LeetCode/#231-Power_Of_Two.cpp
- ONLINE JUDGE/LeetCode/#342-Power_Of_Four.cpp
#231-Power_Of_Two.cpp
#342-Power_Of_Four.cpp
Added the solutions to problems #231 and #342.
Runtime and memory usage is mentioned in the commits.
> Added two more LeetCode problems

- 24- Dynamic Programming/Minimum_Sum_Partition.cpp
**Added the Minimum_Sum_Partition.cpp Filename as**
Minimum Sum Partition Problem:
In this problem given set is partitioned into two subsets such that the difference between the sum of elements of 1st set and the sum of elements of 2nd set is minimized.
**Issue:**
#2
> Minimum Sum Partition.cpp added

- ONLINE JUDGE/LeetCode/#21-Merge-Two-Sorted-Lists.cpp
- ONLINE JUDGE/LeetCode/#26-Remove-Duplicates-From-Sorted-Array.cpp
- ONLINE JUDGE/LeetCode/#27-Remove-Element.cpp
**Added the Filename as**
#21-Merge-Two-Sorted-Lists
#26-Remove-Duplicates-From-Sorted-Array
#27-Remove-Element
**Changes Proposed in the PR. Describe**
added three new leetcode challenges 
- [Y] Yes
> added three LeetCode problems

- ONLINE JUDGE/LeetCode/#628-MaximumProductOfThreeNumbers.cpp
**Added the Filename as**
#628-MaximumProductOfThreeNumbers.cpp
Changes:
Added a solution to a Leet code problem Maximum Product Of Three Numbers using a dp based approach.
I am assuring that the file is not redundant and making the Pull Request
> LeetCode problem 628 solution added

- ONLINE JUDGE/LeetCode/#89- Gray_Code.cpp
> Create #89- Gray_Code.cpp

- 18-Binary Tree/Largest_sum_subtree.cpp
- 18-Binary Tree/build_binary_tree_from_parentArray.cpp
> added build_binary_tree_from_parentArray

- ONLINE JUDGE/LeetCode/#13 Roman to Integer.cpp
- ONLINE JUDGE/LeetCode/#35 Search Insert Position.cpp
- ONLINE JUDGE/LeetCode/#7 Reverse Integer.cpp
**Added the Filenames as**
- #7 Reverse Integer.cpp
- #13 Roman to integer.cpp
- #35 Search Insert position.cpp
I added questions for leetcode as per #13 
> Added 3 Leetcode problems

- 09- Number Theory/Fibonacci number in log(n)
- 13- Linked Lists/Merge Sort.cpp
> Create Merge Sort.cpp

- String/lyndon_factorization.cpp
lyndon_factorization.cpp 
A C++ implementation of duval algorithm to do lyndon factorization of a string.
> Added Lyndon Factorization

- #41- First_missing_positive.cpp
- ONLINE JUDGE/LeetCode/#130-Surrounded-Reason.cpp
- ONLINE JUDGE/LeetCode/#66-Plus_one.cpp
- ONLINE JUDGE/LeetCode/#84-Largest_area_Histogram.cpp
> Largest Area in Histogram

- ONLINE JUDGE/Hackerrank/#29-Cpp exception handling.cpp
> Added HackerRank solution of "Cpp exception handling"

- ONLINE JUDGE/LeetCode/#78- Subsets.cpp
Added "Subset" problem sourced from leetcode "https://leetcode.com/problems/subsets/".
> Create #78- Subsets.cpp

- ONLINE JUDGE/LeetCode/#1052- Grumpy-Bookstore.cpp
Added "Grumpy Bookstore" problem sourced from leetcode "https://leetcode.com/problems/grumpy-bookstore-owner/" along with the thought process in the comments.
> Added Grumpy Bookstore Problem

- 10- Recursion & Backtracking/LCS.cpp
- 10- Recursion & Backtracking/countofSubsetsWithGivenDifference.cpp
- 10- Recursion & Backtracking/countofSubsetsWithgivenSum.cpp
- 10- Recursion & Backtracking/deleteMiddleElementofStackRecursion.cpp
- 10- Recursion & Backtracking/editDistanceRecursive.cpp
- 10- Recursion & Backtracking/isEqualSumPartitionPossible.cpp
- 10- Recursion & Backtracking/isSubsetSumPossible.cpp
- 10- Recursion & Backtracking/sortArrayRecursion.cpp
- 10- Recursion & Backtracking/sortStackDescendingRecursion.cpp
- 24- Dynamic Programming/MCMMemoized.cpp
I have added Matrix Chain Multiplication in DP folder and also added 10 problem codes in the recursion folder
> Added Dynamic Programming and Recursion Problems

- 09- Number Theory/rabinMiller.cpp
Added Rabin Miller Algorithm for finding primes in the Number Theory folder.
Please review my request.
Please do let me know if any changes are to be done!
> Added Rabin Miller Algorithm

- 25-Graph Theory/bipartiteGraphTest.cpp
- 25-Graph Theory/connectedComponents.cpp
- 25-Graph Theory/dijkstras.cpp
Have added some graph theory algorithms in a new folder. Can you please review my request and merge it?
> Added Graph Theory Algorithms

- 24- Dynamic Programming/Knapsack.cpp
> Created a solution to a famous dynamic programming problem "0-1 knapsack"the online judge used for testing is atcoder

- 09- Number Theory/Mobius.cpp
Added Mobius function in the number theory section. Mobius Function is very important in the study of Dirichlet convolution.
#99
> Added Mobius Function in Number Theory

- ONLINE JUDGE/LeetCode/#34- swap-nodes.cpp
Added the Leetcode Question #24- Swap nodes in pairs
> Create #34- swap-nodes.cpp

- 05-Searching/JumpSearch.cpp
> Jump Search

- 24- Dynamic Programming/minFallingPathSumTriangle.cpp
minFallingPathSumTriangle.cpp created
> minFallingPathSumTriangle.cpp created

- 24- Dynamic Programming/longestCommonSubstring.cpp
longestCommonSubstring.cpp created
> longestCommonSubstring.cpp created

- ONLINE JUDGE/CodeChef Challenges/Alternate_Additions.cpp
- ONLINE JUDGE/CodeChef Challenges/Chairs_Requirement.cpp
- ONLINE JUDGE/CodeChef Challenges/Equal_Strings.cpp
- ONLINE JUDGE/CodeChef Challenges/MINSM.cpp
- ONLINE JUDGE/CodeChef Challenges/SEGM01.cpp
- ONLINE JUDGE/CodeChef Challenges/Subscriptions.cpp
submitted code, which are accepted contest time.
change the file name with the problem name only.
- [ x ]  Read [Contribution.md](https://github.com/codewithdev/C-plus-plus-Algorithms/blob/master/CONTRIBUTING.md)
- [ x ]  Created a new branch before committing.
- [ x ]  My File doesn't contain any duplicacy or misinformation (isn't available in the library).
- [ x ]  Added to the right category.
- [ x ]  Described what's being changed.
> added code with right naming convension
